import { ThemeWrapper } from "@/components/theme-wrapper";
import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import "./globals.css";

const assistant = Assistant({
    subsets: ["hebrew"],
    variable: "--font-assistant",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body lang="he">
                <ThemeWrapper>
                    <div
                        dir="rtl"
                        className={`${assistant.className}`}
                    >
                        {children}
                    </div>
                </ThemeWrapper>
            </body>
        </html>
    );
}
